#! /bin/bash

### BEGIN INIT INFO
# Provides:          log-block
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: log-block service
# Description:       Run log-block service
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting log-block"
    sudo perl log-block.pl start
    echo "Start Successfull
    ;;
  stop)
    echo "Stopping log-block"
    sudo perl log-block.pl.pl stop
    echo "Stopped Successfull"
    sleep 2
    ;;
  *)
    echo "Usage: /etc/init.d/log-block {start|stop}"
    exit 1
    ;;
esac

exit 0